baseURL = "https://mmlbzj.github.io/"
languageCode = "zh-CN"
title = "mmlbzj 的技术主页"
theme = "PaperMod"
enableRobotsTXT = true
paginate = 10

[params]
  author = "mmlbzj"
  description = "学习记录 | 运维 | 技术笔记"
  keywords = "博客,Hugo,运维,Linux"
  dateFormat = "2006-01-02"

  # 模式：light / dark / auto
  defaultTheme = "auto"
  showToc = true
  showReadingTime = true
  showWordCount = true
  showShareButtons = true
  comments = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
